name: .NET Test

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: 'The version of .NET to use'
        required: true
        default: '8'
        type: string

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      - name: Run tests
        run: dotnet test --configuration Release
